import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Navbar from '@/component/Navbar'
import FormCompleted from './info-tiles/FormCompleted'
import Processing from './info-tiles/Processing'
import AtEmbassy from './info-tiles/AtEmbassy'
import Approved from './info-tiles/Approved'
import Rejected from './info-tiles/Rejected'

export default function Home() {
	return (
		<>
			<Head>
				<title> Teleport </title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon1.ico" />
			</Head>
			<main className={styles.main}>
				<Navbar />
				<div className={styles.container}>
					<h1 className={styles.mainText}> Welcome to Teleport! </h1>

					<hr />

					<div className={styles.searchbox}>
						<input type="text" placeholder="Search by name, country" />
						<Image className={styles.searchIcon}
							src="search.svg"
							alt="Search icon"
							height={24}
							width={24}
						/>
					</div>

					<div className={styles.subApplication}>
						<h1 className={styles.subText}> Submitted application (5) </h1>
						<hr />
						<FormCompleted /> <hr className="innerhr"/>
						<Processing /> <hr className="innerhr"/>
						<AtEmbassy /> <hr className="innerhr"/>
						<Approved /> <hr className="innerhr"/>
						<Rejected />
					</div>
				</div>
			</main>
		</>
	)
}
